---
# tasks file for itigoag.firefox

- name: gather facts from chocolatey
  win_chocolatey_facts:
  when: ansible_chocolatey is undefined
  tags:
    - configuration
    - packages

- block:

    - name: install firefox
      win_chocolatey:
        name: firefox
      when: >
        packages is undefined or
        not ( string | json_query(query) )
      vars:
        query: '[?package==`firefox`]'
        string: "{{ ansible_chocolatey.packages | lower }}"
      tags:
        - packages

    - name: create distribution directory
      win_file:
        path: "C:\\Program Files\\Mozilla Firefox\\distribution"
        state: directory
      tags:
        - configuration

    - name: create policies file
      win_template:
        src: policies.json.j2
        dest: "C:\\Program Files\\Mozilla Firefox\\distribution\\policies.json"
      tags:
        - configuration

  when: >
    firefox_install and (packages is undefined or packages['firefox'] is defined) or
    packages is defined and packages['firefox'] is defined
